project_name: apkx

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: apkx
    main: ./cmd/apkx/main.go
    binary: apkx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    builds: [apkx]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: 'LICENSE'
        dst: 'LICENSE'
      - src: 'README.md'
        dst: 'README.md'
      - src: 'config/*'
        dst: 'config'
        strip_parent: true

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

signs:
  - artifacts: checksum

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## apkX {{ .Version }} ({{ .Date }})
    
    Welcome to this new release!
  footer: |
    ## Thanks!
    
    * Download the binary for your platform
    * Star the repo if you like it 