version: "3.8"
services:
  apkx-web:
    environment:
      - USE_GITLAB_STORAGE=true
      - GITLAB_BASE_URL=${GITLAB_BASE_URL}
      - GITLAB_PROJECT=${GITLAB_PROJECT_ID}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - IPATOOL_KEYCHAIN_PASSPHRASE=sallam@88
