name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install JADX
        run: |
          JADX_VERSION="1.4.7"
          mkdir -p /tmp/jadx
          cd /tmp/jadx
          wget -q "https://github.com/skylot/jadx/releases/download/v${JADX_VERSION}/jadx-${JADX_VERSION}.zip"
          unzip -q "jadx-${JADX_VERSION}.zip"
          sudo install -m 755 bin/jadx /usr/local/bin/
          sudo install -m 755 bin/jadx-gui /usr/local/bin/
          cd -
          rm -rf /tmp/jadx

      - name: Build
        run: |
          go mod tidy
          go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Create Release Artifact
        if: github.event_name == 'push'
        run: |
          mkdir -p dist
          go build -o dist/apkx ./cmd/apkx/main.go
          tar czf apkx-${{ github.sha }}.tar.gz dist/

      - name: Upload Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: apkx-build
          path: apkx-*.tar.gz
          retention-days: 7